import mongoose from "mongoose";
import dotenv from "dotenv";
import path from "path";
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

dotenv.config({ path: path.join(__dirname, "../.env.local") });

const MONGODB_URI = process.env.MONGODB_URI;

if (!MONGODB_URI) {
  throw new Error("MONGODB_URI not found");
}

const MenuItemSchema = new mongoose.Schema({
  name: { type: String, required: true },
  description: { type: String, required: true },
  calories: { type: Number, required: true },
  protein: { type: Number, required: true },
  carbs: { type: Number, required: true },
  fat: { type: Number, required: true },
  sugar: { type: String, required: true },
  price: { type: Number, required: true },
  category: { type: String, required: true },
  ingredients: [{ type: String }],
  dietaryFlags: [{ type: String }],
  customizationsSupported: [{ type: String }],
});

const MenuItem = mongoose.models.MenuItem || mongoose.model("MenuItem", MenuItemSchema);

// ============================================================
// KANHA RESTAURANT MENU — Real items from menu card
// Nutritional values are approximate based on standard Indian food data
// ============================================================

const kanhaMenu = [
  // ===================== KOFTA SPECIAL =====================
  {
    name: "Malai Kofta Curry",
    description: "Creamy and rich kofta balls in smooth cashew-tomato gravy.",
    calories: 450,
    protein: 12,
    carbs: 35,
    fat: 30,
    sugar: "Medium",
    price: 200,
    category: "Kofta Special",
    ingredients: ["Paneer", "Potato", "Cashew", "Cream", "Tomato", "Onion", "Spices"],
    dietaryFlags: ["Vegetarian"],
    customizationsSupported: ["Less Oil", "Less Spicy", "No Onion", "No Garlic"],
  },
  {
    name: "Paneer Kofta",
    description: "Paneer stuffed kofta in rich tomato-onion gravy.",
    calories: 420,
    protein: 15,
    carbs: 30,
    fat: 28,
    sugar: "Medium",
    price: 180,
    category: "Kofta Special",
    ingredients: ["Paneer", "Potato", "Tomato", "Onion", "Cream", "Spices"],
    dietaryFlags: ["Vegetarian"],
    customizationsSupported: ["Less Oil", "Less Spicy", "No Onion", "No Garlic"],
  },
  {
    name: "Kari Masala Kofta",
    description: "Spiced vegetable kofta in aromatic masala curry.",
    calories: 400,
    protein: 10,
    carbs: 32,
    fat: 26,
    sugar: "Medium",
    price: 200,
    category: "Kofta Special",
    ingredients: ["Mixed Vegetables", "Gram Flour", "Tomato", "Onion", "Spices"],
    dietaryFlags: ["Vegetarian"],
    customizationsSupported: ["Less Oil", "Less Spicy", "No Onion", "No Garlic"],
  },
  {
    name: "Janardhan Kofta",
    description: "Special house-style kofta in a flavourful gravy.",
    calories: 430,
    protein: 11,
    carbs: 34,
    fat: 28,
    sugar: "Medium",
    price: 210,
    category: "Kofta Special",
    ingredients: ["Paneer", "Dry Fruits", "Cream", "Tomato", "Onion", "Spices"],
    dietaryFlags: ["Vegetarian"],
    customizationsSupported: ["Less Oil", "Less Spicy", "No Onion", "No Garlic"],
  },
  {
    name: "Lauki Kofta Curry",
    description: "Light bottle gourd kofta in mild gravy. Good for digestion.",
    calories: 320,
    protein: 8,
    carbs: 28,
    fat: 20,
    sugar: "Low",
    price: 180,
    category: "Kofta Special",
    ingredients: ["Bottle Gourd", "Gram Flour", "Tomato", "Onion", "Spices"],
    dietaryFlags: ["Vegetarian", "Light"],
    customizationsSupported: ["Less Oil", "Less Spicy", "No Onion", "No Garlic"],
  },
  {
    name: "Kofta Kadhi Moti",
    description: "Kofta balls in tangy yogurt-based kadhi gravy.",
    calories: 350,
    protein: 12,
    carbs: 30,
    fat: 22,
    sugar: "Low",
    price: 180,
    category: "Kofta Special",
    ingredients: ["Gram Flour", "Yogurt", "Spices", "Onion"],
    dietaryFlags: ["Vegetarian"],
    customizationsSupported: ["Less Oil", "Less Spicy"],
  },
  {
    name: "Kadhi Boondi Dal",
    description: "Traditional yogurt kadhi with crispy boondi and lentils.",
    calories: 300,
    protein: 10,
    carbs: 35,
    fat: 14,
    sugar: "Low",
    price: 180,
    category: "Kofta Special",
    ingredients: ["Yogurt", "Gram Flour", "Boondi", "Lentils", "Spices"],
    dietaryFlags: ["Vegetarian"],
    customizationsSupported: ["Less Oil", "Less Spicy"],
  },

  // ===================== DAL / SABJI =====================
  {
    name: "Kadai Veg Sabji",
    description: "Mixed vegetables cooked in kadai style with bell peppers and spices.",
    calories: 280,
    protein: 8,
    carbs: 25,
    fat: 18,
    sugar: "Low",
    price: 190,
    category: "Dal Sabji",
    ingredients: ["Mixed Vegetables", "Bell Pepper", "Tomato", "Onion", "Spices"],
    dietaryFlags: ["Vegetarian", "High Fibre"],
    customizationsSupported: ["Less Oil", "Less Spicy", "No Onion", "No Garlic", "Jain"],
  },
  {
    name: "Labdar Dal",
    description: "Thick and flavourful lentil curry with tadka.",
    calories: 250,
    protein: 14,
    carbs: 32,
    fat: 10,
    sugar: "Low",
    price: 160,
    category: "Dal Sabji",
    ingredients: ["Toor Dal", "Tomato", "Onion", "Ghee", "Spices"],
    dietaryFlags: ["Vegetarian", "High Protein"],
    customizationsSupported: ["Less Oil", "Less Spicy", "No Onion", "No Garlic"],
  },
  {
    name: "Rajma Masala",
    description: "Kidney beans in thick spiced tomato gravy. Rich in protein and iron.",
    calories: 310,
    protein: 16,
    carbs: 40,
    fat: 12,
    sugar: "Low",
    price: 180,
    category: "Dal Sabji",
    ingredients: ["Kidney Beans", "Tomato", "Onion", "Ginger", "Garlic", "Spices"],
    dietaryFlags: ["Vegetarian", "Vegan", "High Protein", "High Fibre"],
    customizationsSupported: ["Less Oil", "Less Spicy", "No Onion", "No Garlic"],
  },
  {
    name: "Mix Veg Curry",
    description: "Seasonal mixed vegetables in mildly spiced curry.",
    calories: 250,
    protein: 7,
    carbs: 22,
    fat: 16,
    sugar: "Low",
    price: 180,
    category: "Dal Sabji",
    ingredients: ["Mixed Vegetables", "Tomato", "Onion", "Cream", "Spices"],
    dietaryFlags: ["Vegetarian", "High Fibre"],
    customizationsSupported: ["Less Oil", "Less Spicy", "No Onion", "No Garlic", "Jain"],
  },
  {
    name: "Dum Aloo",
    description: "Baby potatoes slow-cooked in rich Mughlai gravy.",
    calories: 380,
    protein: 6,
    carbs: 40,
    fat: 22,
    sugar: "Medium",
    price: 180,
    category: "Dal Sabji",
    ingredients: ["Potato", "Tomato", "Onion", "Cream", "Cashew", "Spices"],
    dietaryFlags: ["Vegetarian"],
    customizationsSupported: ["Less Oil", "Less Spicy", "No Onion", "No Garlic"],
  },

  // ===================== PANEER SABJI =====================
  {
    name: "Paneer Butter Masala",
    description: "Soft paneer cubes in buttery, creamy tomato gravy. House favourite.",
    calories: 480,
    protein: 18,
    carbs: 25,
    fat: 35,
    sugar: "Medium",
    price: 300,
    category: "Paneer Sabji",
    ingredients: ["Paneer", "Butter", "Cream", "Tomato", "Cashew", "Spices"],
    dietaryFlags: ["Vegetarian", "High Protein"],
    customizationsSupported: ["Less Oil", "Less Butter", "Less Spicy", "No Onion", "No Garlic"],
  },
  {
    name: "Shahi Paneer",
    description: "Royal paneer in rich cashew-cream gravy with mild spices.",
    calories: 460,
    protein: 17,
    carbs: 22,
    fat: 34,
    sugar: "Medium",
    price: 200,
    category: "Paneer Sabji",
    ingredients: ["Paneer", "Cashew", "Cream", "Tomato", "Onion", "Spices"],
    dietaryFlags: ["Vegetarian", "High Protein"],
    customizationsSupported: ["Less Oil", "Less Spicy", "No Onion", "No Garlic"],
  },
  {
    name: "Paneer Bhurji",
    description: "Scrambled paneer with onions, tomatoes and green chillies.",
    calories: 350,
    protein: 20,
    carbs: 12,
    fat: 26,
    sugar: "Low",
    price: 200,
    category: "Paneer Sabji",
    ingredients: ["Paneer", "Onion", "Tomato", "Green Chilli", "Spices"],
    dietaryFlags: ["Vegetarian", "High Protein", "Low Carb"],
    customizationsSupported: ["Less Oil", "Less Spicy", "No Onion"],
  },
  {
    name: "Kadai Paneer",
    description: "Paneer cooked with capsicum and crushed coriander spices in kadai.",
    calories: 400,
    protein: 18,
    carbs: 18,
    fat: 30,
    sugar: "Low",
    price: 250,
    category: "Paneer Sabji",
    ingredients: ["Paneer", "Capsicum", "Tomato", "Onion", "Coriander Seeds", "Spices"],
    dietaryFlags: ["Vegetarian", "High Protein"],
    customizationsSupported: ["Less Oil", "Less Spicy", "No Onion", "No Garlic"],
  },
  {
    name: "Paneer Tikka Masala",
    description: "Tandoor-grilled paneer in spiced tomato-onion masala.",
    calories: 420,
    protein: 20,
    carbs: 20,
    fat: 30,
    sugar: "Low",
    price: 280,
    category: "Paneer Sabji",
    ingredients: ["Paneer", "Yogurt", "Capsicum", "Onion", "Tomato", "Spices"],
    dietaryFlags: ["Vegetarian", "High Protein"],
    customizationsSupported: ["Less Oil", "Less Spicy", "No Onion", "No Garlic"],
  },

  // ===================== PAKODI SABJI =====================
  {
    name: "Pakodi Kadhi",
    description: "Crispy gram flour pakodi in tangy yogurt kadhi.",
    calories: 340,
    protein: 10,
    carbs: 30,
    fat: 20,
    sugar: "Low",
    price: 190,
    category: "Pakodi Sabji",
    ingredients: ["Gram Flour", "Yogurt", "Onion", "Spices"],
    dietaryFlags: ["Vegetarian"],
    customizationsSupported: ["Less Oil", "Less Spicy"],
  },
  {
    name: "Kadhi Pakodi",
    description: "Traditional Rajasthani kadhi with onion pakodi dumplings.",
    calories: 350,
    protein: 10,
    carbs: 32,
    fat: 20,
    sugar: "Low",
    price: 200,
    category: "Pakodi Sabji",
    ingredients: ["Gram Flour", "Yogurt", "Onion", "Spices"],
    dietaryFlags: ["Vegetarian"],
    customizationsSupported: ["Less Oil", "Less Spicy"],
  },
  {
    name: "Kanji Bada Kadhi",
    description: "Fermented mustard water bada in spiced kadhi. Probiotic-rich.",
    calories: 300,
    protein: 9,
    carbs: 28,
    fat: 18,
    sugar: "Low",
    price: 190,
    category: "Pakodi Sabji",
    ingredients: ["Moong Dal", "Mustard Seeds", "Yogurt", "Spices"],
    dietaryFlags: ["Vegetarian", "Probiotic"],
    customizationsSupported: ["Less Oil", "Less Spicy"],
  },

  // ===================== TADKA =====================
  {
    name: "Dahi Tadka",
    description: "Seasoned yogurt with spiced tadka. Cool and probiotic.",
    calories: 200,
    protein: 8,
    carbs: 15,
    fat: 12,
    sugar: "Low",
    price: 300,
    category: "Tadka",
    ingredients: ["Yogurt", "Mustard Seeds", "Curry Leaves", "Green Chilli", "Spices"],
    dietaryFlags: ["Vegetarian", "Probiotic", "Light"],
    customizationsSupported: ["Less Spicy"],
  },
  {
    name: "Dahi Bade",
    description: "Soft lentil dumplings soaked in spiced yogurt. Traditional delicacy.",
    calories: 280,
    protein: 10,
    carbs: 30,
    fat: 14,
    sugar: "Low",
    price: 170,
    category: "Tadka",
    ingredients: ["Urad Dal", "Yogurt", "Tamarind Chutney", "Cumin", "Spices"],
    dietaryFlags: ["Vegetarian", "Probiotic"],
    customizationsSupported: ["Less Spicy", "Less Oil"],
  },
  {
    name: "Kadhi Papad",
    description: "Yogurt-based kadhi with crispy papad pieces.",
    calories: 260,
    protein: 8,
    carbs: 25,
    fat: 14,
    sugar: "Low",
    price: 120,
    category: "Tadka",
    ingredients: ["Yogurt", "Gram Flour", "Papad", "Spices"],
    dietaryFlags: ["Vegetarian"],
    customizationsSupported: ["Less Spicy", "Less Oil"],
  },

  // ===================== DAL =====================
  {
    name: "Dal Makhani",
    description: "Slow-cooked black lentils in creamy butter gravy. Rich and wholesome.",
    calories: 380,
    protein: 14,
    carbs: 35,
    fat: 22,
    sugar: "Low",
    price: 190,
    category: "Dal",
    ingredients: ["Black Urad Dal", "Rajma", "Butter", "Cream", "Tomato", "Spices"],
    dietaryFlags: ["Vegetarian", "High Protein"],
    customizationsSupported: ["Less Butter", "Less Oil", "Less Spicy"],
  },
  {
    name: "Dal Tadka",
    description: "Yellow lentils tempered with ghee, cumin and garlic.",
    calories: 240,
    protein: 12,
    carbs: 30,
    fat: 10,
    sugar: "Low",
    price: 150,
    category: "Dal",
    ingredients: ["Toor Dal", "Ghee", "Cumin", "Garlic", "Tomato", "Spices"],
    dietaryFlags: ["Vegetarian", "High Protein", "Light"],
    customizationsSupported: ["Less Oil", "Less Spicy", "No Garlic"],
  },
  {
    name: "Dal Mix",
    description: "Combination of multiple lentils cooked together. Nutritious.",
    calories: 260,
    protein: 14,
    carbs: 32,
    fat: 10,
    sugar: "Low",
    price: 130,
    category: "Dal",
    ingredients: ["Toor Dal", "Moong Dal", "Masoor Dal", "Chana Dal", "Spices"],
    dietaryFlags: ["Vegetarian", "Vegan", "High Protein", "High Fibre"],
    customizationsSupported: ["Less Oil", "Less Spicy", "No Onion", "No Garlic"],
  },
  {
    name: "Dal Palak",
    description: "Lentils cooked with fresh spinach. Iron-rich and nutritious.",
    calories: 230,
    protein: 13,
    carbs: 28,
    fat: 8,
    sugar: "Low",
    price: 150,
    category: "Dal",
    ingredients: ["Toor Dal", "Spinach", "Tomato", "Garlic", "Spices"],
    dietaryFlags: ["Vegetarian", "High Protein", "Iron Rich", "Light"],
    customizationsSupported: ["Less Oil", "Less Spicy", "No Garlic"],
  },
  {
    name: "Arhar Dal",
    description: "Simple and light pigeon pea lentil. Easy on stomach.",
    calories: 210,
    protein: 12,
    carbs: 28,
    fat: 6,
    sugar: "Low",
    price: 130,
    category: "Dal",
    ingredients: ["Arhar Dal", "Tomato", "Ghee", "Cumin", "Spices"],
    dietaryFlags: ["Vegetarian", "Vegan", "High Protein", "Light", "Easy to Digest"],
    customizationsSupported: ["Less Oil", "Less Spicy", "No Onion", "No Garlic", "Jain"],
  },
  {
    name: "Dal Panchmel",
    description: "Rajasthani five-lentil mix dal. Rich in protein and fibre.",
    calories: 270,
    protein: 15,
    carbs: 33,
    fat: 10,
    sugar: "Low",
    price: 150,
    category: "Dal",
    ingredients: ["Chana Dal", "Toor Dal", "Moong Dal", "Masoor Dal", "Urad Dal", "Ghee", "Spices"],
    dietaryFlags: ["Vegetarian", "High Protein", "High Fibre"],
    customizationsSupported: ["Less Oil", "Less Spicy", "No Onion", "No Garlic"],
  },

  // ===================== ROTI / PARATHA =====================
  {
    name: "Butter Tawa Roti",
    description: "Fresh whole wheat roti with butter on tawa.",
    calories: 120,
    protein: 3,
    carbs: 18,
    fat: 4,
    sugar: "Low",
    price: 8,
    category: "Roti / Paratha",
    ingredients: ["Whole Wheat Flour", "Butter"],
    dietaryFlags: ["Vegetarian"],
    customizationsSupported: ["No Butter"],
  },
  {
    name: "Kathi Tawa Roti",
    description: "Layered roti cooked on tawa. Slightly crispy.",
    calories: 130,
    protein: 3,
    carbs: 20,
    fat: 5,
    sugar: "Low",
    price: 12,
    category: "Roti / Paratha",
    ingredients: ["Whole Wheat Flour", "Oil"],
    dietaryFlags: ["Vegetarian"],
    customizationsSupported: ["Less Oil"],
  },
  {
    name: "Tawa Roti",
    description: "Plain whole wheat roti. Simple and healthy.",
    calories: 90,
    protein: 3,
    carbs: 18,
    fat: 1,
    sugar: "Low",
    price: 8,
    category: "Roti / Paratha",
    ingredients: ["Whole Wheat Flour"],
    dietaryFlags: ["Vegetarian", "Vegan", "Light"],
    customizationsSupported: [],
  },
  {
    name: "Missi Roti",
    description: "Gram flour and wheat flour roti with spices. High in protein.",
    calories: 160,
    protein: 6,
    carbs: 22,
    fat: 6,
    sugar: "Low",
    price: 40,
    category: "Roti / Paratha",
    ingredients: ["Gram Flour", "Wheat Flour", "Onion", "Green Chilli", "Spices"],
    dietaryFlags: ["Vegetarian", "High Protein"],
    customizationsSupported: ["No Onion", "Less Spicy"],
  },
  {
    name: "Masala Paratha",
    description: "Spiced whole wheat paratha. Flavourful and filling.",
    calories: 200,
    protein: 5,
    carbs: 25,
    fat: 10,
    sugar: "Low",
    price: 40,
    category: "Roti / Paratha",
    ingredients: ["Wheat Flour", "Spices", "Oil"],
    dietaryFlags: ["Vegetarian"],
    customizationsSupported: ["Less Oil", "Less Spicy"],
  },
  {
    name: "Plain Paratha",
    description: "Simple layered wheat paratha cooked on tawa.",
    calories: 180,
    protein: 4,
    carbs: 24,
    fat: 8,
    sugar: "Low",
    price: 30,
    category: "Roti / Paratha",
    ingredients: ["Wheat Flour", "Oil"],
    dietaryFlags: ["Vegetarian"],
    customizationsSupported: ["Less Oil"],
  },
  {
    name: "Aloo Paratha",
    description: "Wheat paratha stuffed with spiced potato filling.",
    calories: 280,
    protein: 6,
    carbs: 35,
    fat: 14,
    sugar: "Low",
    price: 50,
    category: "Roti / Paratha",
    ingredients: ["Wheat Flour", "Potato", "Green Chilli", "Coriander", "Spices", "Butter"],
    dietaryFlags: ["Vegetarian"],
    customizationsSupported: ["Less Oil", "Less Spicy", "No Butter"],
  },
  {
    name: "Gobhi Paratha",
    description: "Paratha stuffed with spiced cauliflower filling.",
    calories: 260,
    protein: 6,
    carbs: 30,
    fat: 14,
    sugar: "Low",
    price: 50,
    category: "Roti / Paratha",
    ingredients: ["Wheat Flour", "Cauliflower", "Green Chilli", "Spices", "Butter"],
    dietaryFlags: ["Vegetarian"],
    customizationsSupported: ["Less Oil", "Less Spicy", "No Butter"],
  },
  {
    name: "Paneer Paratha",
    description: "Paratha stuffed with spiced paneer filling. High protein.",
    calories: 320,
    protein: 12,
    carbs: 28,
    fat: 18,
    sugar: "Low",
    price: 70,
    category: "Roti / Paratha",
    ingredients: ["Wheat Flour", "Paneer", "Green Chilli", "Spices", "Butter"],
    dietaryFlags: ["Vegetarian", "High Protein"],
    customizationsSupported: ["Less Oil", "Less Spicy", "No Butter"],
  },
  {
    name: "Mooli Paratha",
    description: "Paratha stuffed with spiced radish. Light and easy to digest.",
    calories: 220,
    protein: 5,
    carbs: 28,
    fat: 10,
    sugar: "Low",
    price: 40,
    category: "Roti / Paratha",
    ingredients: ["Wheat Flour", "Radish", "Green Chilli", "Spices"],
    dietaryFlags: ["Vegetarian", "Light"],
    customizationsSupported: ["Less Oil", "Less Spicy"],
  },
  {
    name: "Pyaz Paratha",
    description: "Paratha stuffed with spiced onion filling.",
    calories: 230,
    protein: 5,
    carbs: 28,
    fat: 12,
    sugar: "Low",
    price: 40,
    category: "Roti / Paratha",
    ingredients: ["Wheat Flour", "Onion", "Green Chilli", "Spices"],
    dietaryFlags: ["Vegetarian"],
    customizationsSupported: ["Less Oil", "Less Spicy"],
  },
  {
    name: "Methi Paratha",
    description: "Paratha with fresh fenugreek leaves. Good for diabetes management.",
    calories: 210,
    protein: 6,
    carbs: 26,
    fat: 10,
    sugar: "Low",
    price: 50,
    category: "Roti / Paratha",
    ingredients: ["Wheat Flour", "Fenugreek Leaves", "Spices"],
    dietaryFlags: ["Vegetarian", "Diabetic Friendly"],
    customizationsSupported: ["Less Oil", "Less Spicy"],
  },
  {
    name: "Laccha Paratha",
    description: "Layered flaky paratha. Crispy and buttery.",
    calories: 280,
    protein: 5,
    carbs: 30,
    fat: 16,
    sugar: "Low",
    price: 40,
    category: "Roti / Paratha",
    ingredients: ["Wheat Flour", "Ghee", "Oil"],
    dietaryFlags: ["Vegetarian"],
    customizationsSupported: ["Less Oil"],
  },

  // ===================== CHAWAL (RICE) SPECIAL =====================
  {
    name: "Jeera Rice",
    description: "Basmati rice tempered with cumin seeds. Light and aromatic.",
    calories: 250,
    protein: 5,
    carbs: 45,
    fat: 6,
    sugar: "Low",
    price: 150,
    category: "Chawal Special",
    ingredients: ["Basmati Rice", "Cumin Seeds", "Ghee"],
    dietaryFlags: ["Vegetarian", "Vegan", "Gluten Free"],
    customizationsSupported: ["Less Ghee"],
  },
  {
    name: "Plain Rice",
    description: "Steamed basmati rice. Simple and light.",
    calories: 200,
    protein: 4,
    carbs: 44,
    fat: 1,
    sugar: "Low",
    price: 120,
    category: "Chawal Special",
    ingredients: ["Basmati Rice"],
    dietaryFlags: ["Vegetarian", "Vegan", "Gluten Free", "Light"],
    customizationsSupported: [],
  },
  {
    name: "Veg Biryani",
    description: "Fragrant basmati rice cooked with mixed vegetables and biryani spices.",
    calories: 380,
    protein: 8,
    carbs: 52,
    fat: 16,
    sugar: "Low",
    price: 180,
    category: "Chawal Special",
    ingredients: ["Basmati Rice", "Mixed Vegetables", "Yogurt", "Biryani Masala", "Ghee", "Spices"],
    dietaryFlags: ["Vegetarian"],
    customizationsSupported: ["Less Oil", "Less Spicy"],
  },
  {
    name: "Kashmiri Pulao",
    description: "Sweet and mild rice with dry fruits, saffron and mixed fruits.",
    calories: 350,
    protein: 6,
    carbs: 50,
    fat: 14,
    sugar: "Medium",
    price: 190,
    category: "Chawal Special",
    ingredients: ["Basmati Rice", "Dry Fruits", "Saffron", "Ghee", "Fruits"],
    dietaryFlags: ["Vegetarian", "Gluten Free"],
    customizationsSupported: ["Less Ghee"],
  },
  {
    name: "Dal Khichdi",
    description: "Comforting rice and lentil porridge. Easy to digest, perfect for recovery.",
    calories: 280,
    protein: 10,
    carbs: 40,
    fat: 8,
    sugar: "Low",
    price: 130,
    category: "Chawal Special",
    ingredients: ["Rice", "Moong Dal", "Ghee", "Cumin", "Turmeric", "Spices"],
    dietaryFlags: ["Vegetarian", "Gluten Free", "Light", "Easy to Digest"],
    customizationsSupported: ["Less Ghee", "Less Spicy"],
  },

  // ===================== TANDOOR + SALAD =====================
  {
    name: "Tandoor Salad",
    description: "Fresh salad with tandoor-roasted vegetables.",
    calories: 80,
    protein: 3,
    carbs: 10,
    fat: 4,
    sugar: "Low",
    price: 25,
    category: "Tandoor + Salad",
    ingredients: ["Cucumber", "Tomato", "Onion", "Carrot", "Lemon"],
    dietaryFlags: ["Vegetarian", "Vegan", "Gluten Free", "Low Calorie"],
    customizationsSupported: ["No Onion"],
  },
  {
    name: "Green Salad",
    description: "Fresh green vegetables with lemon dressing.",
    calories: 50,
    protein: 2,
    carbs: 8,
    fat: 2,
    sugar: "Low",
    price: 25,
    category: "Tandoor + Salad",
    ingredients: ["Cucumber", "Lettuce", "Coriander", "Lemon"],
    dietaryFlags: ["Vegetarian", "Vegan", "Gluten Free", "Low Calorie"],
    customizationsSupported: [],
  },
  {
    name: "Boondi Raita",
    description: "Yogurt with crispy boondi and spices. Cooling side dish.",
    calories: 120,
    protein: 4,
    carbs: 14,
    fat: 5,
    sugar: "Low",
    price: 25,
    category: "Tandoor + Salad",
    ingredients: ["Yogurt", "Boondi", "Cumin", "Salt"],
    dietaryFlags: ["Vegetarian", "Probiotic"],
    customizationsSupported: [],
  },
  {
    name: "Papad Raita",
    description: "Yogurt with crushed papad. Crunchy and cooling.",
    calories: 130,
    protein: 5,
    carbs: 15,
    fat: 5,
    sugar: "Low",
    price: 25,
    category: "Tandoor + Salad",
    ingredients: ["Yogurt", "Papad", "Cumin", "Salt"],
    dietaryFlags: ["Vegetarian", "Probiotic"],
    customizationsSupported: [],
  },

  // ===================== DESSERT / SWEETS =====================
  {
    name: "Gulab Jamun",
    description: "Deep-fried milk dumplings soaked in cardamom sugar syrup.",
    calories: 180,
    protein: 3,
    carbs: 28,
    fat: 7,
    sugar: "High",
    price: 15,
    category: "Dessert",
    ingredients: ["Khoya", "Flour", "Sugar Syrup", "Cardamom"],
    dietaryFlags: ["Vegetarian"],
    customizationsSupported: [],
  },
  {
    name: "Rasgulla",
    description: "Soft spongy cottage cheese balls in light sugar syrup.",
    calories: 150,
    protein: 4,
    carbs: 25,
    fat: 4,
    sugar: "High",
    price: 15,
    category: "Dessert",
    ingredients: ["Chenna", "Sugar Syrup", "Cardamom"],
    dietaryFlags: ["Vegetarian"],
    customizationsSupported: [],
  },
  {
    name: "Kesar Kheer",
    description: "Traditional saffron-infused rice pudding with nuts.",
    calories: 220,
    protein: 6,
    carbs: 32,
    fat: 8,
    sugar: "High",
    price: 25,
    category: "Dessert",
    ingredients: ["Milk", "Rice", "Sugar", "Saffron", "Dry Fruits"],
    dietaryFlags: ["Vegetarian"],
    customizationsSupported: ["Less Sugar"],
  },

  // ===================== SIDE DISH =====================
  {
    name: "Maharaja Dal",
    description: "Premium five-lentil preparation with rich butter and cream. House special.",
    calories: 350,
    protein: 15,
    carbs: 32,
    fat: 20,
    sugar: "Low",
    price: 190,
    category: "Side Dish",
    ingredients: ["Mixed Lentils", "Butter", "Cream", "Tomato", "Spices"],
    dietaryFlags: ["Vegetarian", "High Protein"],
    customizationsSupported: ["Less Butter", "Less Cream", "Less Spicy"],
  },

  // ===================== DAAL (Dal section continued) =====================
  {
    name: "Dal Makhani (Special)",
    description: "Chef's special slow-cooked dal makhani with extra butter finish.",
    calories: 400,
    protein: 14,
    carbs: 34,
    fat: 24,
    sugar: "Low",
    price: 190,
    category: "Dal",
    ingredients: ["Black Urad Dal", "Rajma", "Butter", "Cream", "Tomato", "Kasuri Methi"],
    dietaryFlags: ["Vegetarian", "High Protein"],
    customizationsSupported: ["Less Butter", "Less Oil", "Less Spicy"],
  },
];

async function seed() {
  try {
    await mongoose.connect(MONGODB_URI);
    console.log("Connected to DB");
    
    await MenuItem.deleteMany({});
    console.log("Cleared old menu items");

    await MenuItem.insertMany(kanhaMenu);
    console.log(`Inserted ${kanhaMenu.length} Kanha menu items`);
    
    // Print summary
    const categories = [...new Set(kanhaMenu.map(i => i.category))];
    console.log("\nMenu Summary:");
    for (const cat of categories) {
      const items = kanhaMenu.filter(i => i.category === cat);
      console.log(`  ${cat}: ${items.length} items (₹${Math.min(...items.map(i => i.price))} - ₹${Math.max(...items.map(i => i.price))})`);
    }
    
    process.exit(0);
  } catch (error) {
    console.error(error);
    process.exit(1);
  }
}

seed();
